no-resolv
listen-address=127.0.0.1
bind-interfaces
cache-size=10000



# 1. По умолчанию — Google DNS
server=8.8.8.8
server=8.8.4.4
nftset=/#/4#inet#vpnroute#amnezia4



# 2. Корпоративная зона

# 3. Зона без впн
server=/.ru/77.88.8.8
server=/.ru/77.88.8.1
nftset=/.ru/4#inet#vpnroute#novpn4

server=/vk.com/77.88.8.8
server=/vk.com/77.88.8.1
nftset=/vk.com/4#inet#vpnroute#novpn4

# vk
server=/userapi.com/77.88.8.8
server=/userapi.com/77.88.8.1
nftset=/userapi.com/4#inet#vpnroute#novpn4

# vk
server=/mycdn.me/77.88.8.8
server=/mycdn.me/77.88.8.1
nftset=/mycdn.me/4#inet#vpnroute#novpn4

server=/cian.site/77.88.8.8
server=/cian.site/77.88.8.1
